# Generated by Django 5.0.6 on 2024-08-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_initial_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('real_estate', 'Real Estate'), ('vehicles', 'Vehicles'), ('artworks_antiques_collectibles', 'Artworks, Antiques, Collectibles'), ('jewelry_luxuries', 'Jewelry, Luxuries'), ('technology_electronics_engineering', 'Technology, Electronics, Engineering'), ('others', 'Others')], default='others', max_length=100),
        ),
    ]
