# Generated by Django 5.0.6 on 2024-07-31 16:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='time',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='bid_increment',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='starting_price',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='auctionparticipant',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='auctionparticipant',
            name='deposit_date',
        ),
        migrations.RemoveField(
            model_name='auctionparticipant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='status',
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
        migrations.CreateModel(
            name='AuctionItemParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_date', models.DateTimeField(auto_now_add=True)),
                ('auction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_participants', to='auctions.auctionitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('auction_item', 'user')},
            },
        ),
    ]
