# Generated by Django 5.0.6 on 2024-07-30 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-sent_date']},
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
