# Generated by Django 5.0.6 on 2024-07-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usernotification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='sent_date',
            field=models.DateTimeField(),
        ),
    ]
